### PR TITLE
Workflows for binary releases

### PR DESCRIPTION
**Pull request by ghost**
## Changes introduced with this PR

This PR adds workflows for creating binary releases for Arcaflow.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by HubertStefanski — APPROVED** [review]
LGTM, just one nitpick, are we pro or against EOF newlines?

**Comment by sandrobonazzola** [comment]
> @HubertStefanski I don't really care, @sandrobonazzola likes them. :D For Go we use whatever gofmt spits out.

Indeed, please add EOF newlines :-)

**Review by jaredoconnell — APPROVED** [review]
Looks good to me.

I fixed one file name mismatch and I made the files end in a new line.

**Review by portante — APPROVED** [review]
Ship it!

**Pull request merged**
